### ISSUE TITLE
Add a Custom Elements Manifest

### ISSUE THREAD

**Issue by jogibear9988** [christianliebel/paint#311]
@christianliebel 
hy, I added your paint app to my webcomponent designer as a sample.
https://github.com/node-projects/web-component-designer-demo

If you don't like, I'll remove it

**Comment by jogibear9988** [comment]
And would it make sense to add other components of your lib?

**Comment by christianliebel** [comment]
Sure, feel free to use it. The only other component I could think of is the `paint-button` which I introduced yesterday. All other components are pretty much tied to the application.

Very cool designer, by the way. Looks I need to embed the taskbar icons as well.

**Comment by jogibear9988** [comment]
@christianliebel 
Thanks.

will you also create a npm package? 
and maybe when it's ready a https://github.com/webcomponents/custom-elements-manifest

**Comment by christianliebel** [comment]
I didn't plan to introduce an npm package until now. It definitely makes sense, but as it would require some infrastructure (e.g., release management), I would try to avoid it for now. (-> #320) Would the GitHub dependency work for the moment when the error is gone?

I can surely add a custom elements manifest to this repository and will update the title of this issue accordingly.
