### ISSUE TITLE
Error using as NPM Package

### ISSUE THREAD

**Issue by jogibear9988** [christianliebel/paint#317]
This what I try now, worked yesterday...

I add you repo as node_module to my designer.
Then I go to the directory node_modules/paint and build it

     npm run build

but there ar eno output files.

Also a "npx run tsc " does not generate any files

And also "npm start" does not work.

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/120636220-a7c33680-c46d-11eb-8135-06fbc720f0e5.png)

**Comment by christianliebel** [comment]
There were indeed some changes since yesterday, as I had to downgrade to an earlier version of Snowpack. However, that works on my machine (event after a `git clean`) and it also works on the CI server: https://github.com/christianliebel/paint/runs/2735591540

Could you try purging your entire node_modules folder and installing it again?

**Comment by jogibear9988** [comment]
Same problem.

But as I said, I don't use git to clone your repo, I install paint as a npm module inside of my webcomponent designer demo.

**Comment by christianliebel** [comment]
I just tried the following:

```sh
mkdir foo
cd foo
npm init # + wizard
npm i github:christianliebel/paint
cd node_modules/paint
npm i
npm run build
```

And that does it for me…

**Comment by jogibear9988** [comment]
build does work

![image](https://user-images.githubusercontent.com/364896/120652296-efeb5480-c47f-11eb-9877-0b39d79305d9.png)

but there is no build folder after

**Comment by christianliebel** [comment]
I see. This appears to be a bug in the particular version of Snowpack that I use… Alright, I'll revert that change. `npm start` will break in the meantime, I will document it in the README.

**Comment by christianliebel** [comment]
Mh, to no avail, as I need a working dev build. I'll prioritize the npm package. Could you please use `github:christianliebel/paint#e811a98` as a dependency in the meantime?

**Comment by christianliebel** [comment]
@jogibear9988 You can now use [@christianliebel/paint](https://www.npmjs.com/package/@christianliebel/paint) 🎉
